from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware

from schema import HeartData
from predict import predict

app = FastAPI(
    title="Heart Disease Prediction API",
    version="1.0.0"
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


@app.get("/")
def home():
    return {
        "status": "success",
        "message": "Heart Disease Prediction API is Running"
    }


@app.get("/health")
def health():
    return {
        "status": "healthy"
    }


@app.post("/predict")
def predict_disease(data: HeartData):
    try:
        result = predict(data)

        # SageMaker response
        prediction = int(result["predictions"][0])

        # Updated Target Mapping
        # 1 = No Heart Disease (Low Risk)
        # 0 = Heart Disease (High Risk)

        if prediction == 1:
            risk = "Low"
            message = "No Heart Disease"
        else:
            risk = "High"
            message = "Heart Disease Detected"

        return {
            "status": "success",
            "prediction": prediction,
            "risk": risk,
            "result": message,
            "note": "This prediction is generated by a machine learning model and should not be considered a medical diagnosis. Please consult a healthcare professional."
        }

    except Exception as e:
        raise HTTPException(
            status_code=500,
            detail=f"Prediction failed: {str(e)}"
        )